FROM ghcr.io/graalvm/native-image-community:25

ENV MAVEN_VERSION=3.9.11
ENV MAVEN_HOME="/opt/apache-maven-$MAVEN_VERSION"
RUN curl -s -L "https://maven.apache.org/download.cgi?action=download&filename=maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz" -o "apache-maven-$MAVEN_VERSION-bin.tar.gz" \
  && curl -s -L "https://downloads.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz.sha512" -o "apache-maven-$MAVEN_VERSION-bin.tar.gz.sha512" \
  && echo "$(cat apache-maven-$MAVEN_VERSION-bin.tar.gz.sha512)  apache-maven-$MAVEN_VERSION-bin.tar.gz" | sha512sum -c \
  && tar -xzf "apache-maven-$MAVEN_VERSION-bin.tar.gz" -C /opt \
  && rm -f apache-maven*.tar.gz*

ENV PATH="$MAVEN_HOME/bin:$PATH"

ENTRYPOINT []
