logging:
  pattern:
    level: "%5level op:%3mdc{op}"

spring:
  main:
    banner-mode: "off"
  shell:
    command:
      history:
        enabled: false
      script:
        enabled: false
    history:
      enabled: false
    option:
      naming:
        case-type: kebab
