logging:
  level:
    org:
      syphr:
        emulator:
          cli:
            Application: warn
  pattern:
    level: "%5level clock:%6mdc{clock} op:%4mdc{op}"

spring:
  main:
    banner-mode: "off"
  shell:
    command:
      history:
        enabled: false
      script:
        enabled: false
    history:
      enabled: false
    option:
      naming:
        case-type: kebab
