name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Verify License Headers
        run: mvn --batch-mode --file pom.xml license:check

      - name: Build and Test
        run: mvn --batch-mode --file pom.xml verify

      # Improve the quality of Dependabot alerts this repository can receive
      # FIXME: Disabled due to "TypeError: Cannot read properties of undefined (reading 'forEach')"
#      - name: Update dependency graph
#        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
